"use strict";
(() => {
  const API = "/graci/visualizer/v1";
  const SNAPSHOT_INTERVAL_MS = 3000;
  const MAX_EVENT_ROWS = 100;
  const PRESENCE_BY_STATE = Object.freeze({
    "idle":"resting", "listening":"receptive", "planning":"thinking",
    "retrieving_memory":"thinking", "reasoning":"thinking", "executing_tool":"acting",
    "testing":"validating", "reviewing":"validating", "adjudicating":"validating",
    "completed":"success", "warning":"warning", "failed":"failure", "speaking":"responding"
  });
  const SAFE_PRESENCE = "warning";
  const presenceFor = (systemState) => PRESENCE_BY_STATE[systemState] || SAFE_PRESENCE;
  const ALL_STATES = Object.freeze(Object.keys(PRESENCE_BY_STATE));
  const ALL_SEVERITIES = ["info","activity","success","warning","error"];
  const $ = (id) => document.getElementById(id);
  const state = { snapshot: null, events: new Map(), lastSuccess: 0, eventSource: null };
  const text = (value, fallback = "—") => value === null || value === undefined || value === "" ? fallback : String(value).replaceAll("_", " ").toUpperCase();
  const localTime = (value, seconds = true) => { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? "—" : date.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:seconds?"2-digit":undefined}); };
  const shortId = (value) => value ? String(value).slice(0, 14) : "—";
  const field = (root, name, value) => { const node = root.querySelector(`[data-field="${name}"]`); if (node) node.textContent = text(value); };
  function connection(kind, label) { document.body.dataset.connection = kind; const node=$("connection"); node.className=`connection ${kind}`; node.innerHTML=`<i></i> ${label}`; document.body.classList.toggle("stale", kind === "disconnected"); }
  function renderNode(id, node) {
    const root=$(id); if (!node) return; const blocked=node.node_id === "4090" && (node.eligible === false || node.mo2_state === "running");
    const available=node.endpoint_health === "healthy" && !blocked; root.dataset.status=blocked?"blocked":available?"available":node.endpoint_health === "unhealthy"?"failed":"unknown";
    root.querySelector(".availability").textContent=blocked?"BLOCKED — MO2 RUNNING":available?"AVAILABLE / HEALTHY":text(node.availability);
    field(root,"health",node.endpoint_health); field(root,"model",node.assigned_model,"UNASSIGNED"); field(root,"role",node.assigned_role || node.role); field(root,"mo2",node.mo2_state,"NOT OBSERVED"); field(root,"eligibility",node.eligible===true?"ELIGIBLE":node.eligible===false?"BLOCKED":"UNKNOWN"); field(root,"reason",node.policy_reason,"NO POLICY RESTRICTION");
  }
  function renderAgent(id, agent) { const root=$(id); if(!agent)return; field(root,"model",agent.model_id); field(root,"activity",agent.activity || agent.review_status || agent.state); root.dataset.status=agent.state; }
  function setStage(name,status,label) { const root=document.querySelector(`[data-stage="${name}"]`); if(!root)return; root.dataset.status=status; root.querySelector("b").textContent=text(label || status); }
  function renderPipeline(s) {
    const active=s.system_state; const memory=s.memory.requested ? (active==="retrieving_memory"?"active":s.memory.supplied_memory_ids.length?"passed":"pending") : "not_applicable";
    const ops=s.execution.operations||[]; const opFailed=ops.some(x=>x.status==="failed"); const opActive=ops.some(x=>x.status==="active");
    setStage("memory",memory); setStage("qwen",s.agents.qwen.state,s.agents.qwen.activity||s.agents.qwen.state); setStage("tools",opFailed?"failed":opActive||active==="executing_tool"?"active":ops.length?"passed":"not_applicable"); setStage("tests",s.execution.tests.status); setStage("review",s.review.reviewer_status); setStage("adjudication",s.review.adjudication_status);
  }
  function renderLatestTurn(turn) {
    const panel=document.querySelector(".operator-response");
    if(!turn){panel.dataset.status="none";$("latest-turn-status").textContent="NONE";$("latest-turn-id").textContent="NO RESIDENT RESULT";$("latest-turn-presentation").textContent="PRESENTATION N/A";$("operator-response").textContent="No completed resident turn yet.";return;}
    panel.dataset.status=turn.governed_status;$("latest-turn-status").textContent=text(turn.governed_status);$("latest-turn-id").textContent=`RUN ${shortId(turn.run_id)} · ${localTime(turn.completed_at)}`;$("latest-turn-presentation").textContent=`PRESENTATION ${text(turn.presentation_outcome)}`;$("operator-response").textContent=turn.response_available?turn.response_text:(turn.failure_reason||"No validated authoritative response is available for this completed turn.");
  }
  function renderSnapshot(s) {
    state.snapshot=s; state.lastSuccess=Date.now(); connection("live","LIVE"); const presence=presenceFor(s.system_state); document.body.dataset.systemState=ALL_STATES.includes(s.system_state)?s.system_state:"warning"; document.body.dataset.presence=presence;
    $("overall-state").textContent=text(s.system_state,"UNKNOWN"); $("core-state").textContent=text(s.system_state,"UNKNOWN"); $("presence-category").textContent=text(presence); $("schema").textContent=`v${s.schema_version}`; $("snapshot-id").textContent=shortId(s.snapshot_id); $("updated").textContent=localTime(s.generated_at); $("freshness").textContent="LIVE OBSERVED STATE";
    renderNode("node-3090",s.compute.primary_3090); renderNode("node-4090",s.compute.optional_4090); renderAgent("agent-qwen",s.agents.qwen); renderAgent("agent-glm",s.agents.glm); renderLatestTurn(s.latest_turn); updatePTTAvailability(); $("restart-button").classList.toggle("visible",s.system_state==="failed");
    const task=s.task, hasTask=Boolean(task.task_id); $("task-summary").textContent=hasTask?(task.summary||"BOUNDED TASK"):"SYSTEM AT REST"; $("task-id").textContent=shortId(task.task_id); $("task-phase").textContent=text(task.phase,hasTask?text(s.system_state):"IDLE"); $("task-started").textContent=localTime(task.started_at);
    const pct=task.progress_total?Math.min(100,Math.round(task.progress_current/task.progress_total*100)):0; $("task-progress").style.width=`${pct}%`; $("task-status").textContent=task.failure_reason|| (hasTask?`${text(task.final_status)} · ${pct}% observed progress`:"No current task. Monitoring local runtime.");
    const m=s.memory; document.querySelector(".memory-panel").classList.toggle("active",m.requested); $("memory-status").textContent=text(m.selection_status,m.requested?"REQUESTED":"N/A"); $("memory-mode").textContent=text(m.mode); $("memory-keys").textContent=m.relevance_keys.length; $("memory-selected").textContent=m.selected_memory_ids.length; $("memory-supplied").textContent=m.supplied_memory_ids.length; $("memory-context").textContent=Number(m.context_characters).toLocaleString(); $("memory-diag").textContent=`${m.conflict_count} / ${m.corruption_count}`;
    const review=$("review-panel"), adjudication=$("adjudication-panel"); review.querySelector("strong").textContent=text(s.review.structured_verdict||s.review.reviewer_status); review.dataset.status=s.review.reviewer_status; adjudication.querySelector("strong").textContent=text(s.review.final_outcome||s.review.adjudication_status); adjudication.dataset.status=s.review.adjudication_status;
    renderPipeline(s); renderOperations(s.execution.operations||[]); (s.recent_events||[]).forEach(addEvent); renderEvents();
  }
  function renderOperations(ops) { const root=$("operations"); const rows=ops.slice(-12).reverse(); root.innerHTML=rows.length?rows.map(op=>`<div class="operation" data-status="${op.status}"><b>${text(op.category)}</b><span>${escapeHtml(op.target_label||"BOUNDED OPERATION")}</span><em>${text(op.status)}</em></div>`).join(""):'<p class="empty">No execution operations observed.</p>'; }
  function escapeHtml(value) { const e=document.createElement("span"); e.textContent=String(value); return e.innerHTML; }
  function addEvent(event) { if(!event||!event.event_id||!ALL_SEVERITIES.includes(event.severity)||state.events.has(event.event_id))return; state.events.set(event.event_id,event); while(state.events.size>MAX_EVENT_ROWS)state.events.delete(state.events.keys().next().value); }
  function renderEvents() { const values=[...state.events.values()].slice(-MAX_EVENT_ROWS).reverse(); $("event-count").textContent=`${values.length} / ${MAX_EVENT_ROWS}`; $("events").innerHTML=values.length?values.map(e=>`<div class="event" data-severity="${e.severity}"><time title="${escapeHtml(e.timestamp)}">${localTime(e.timestamp)}</time><b>${text(e.event_type)}</b><small>${text(e.source)}</small><span>${escapeHtml(e.message)}</span></div>`).join(""):'<p class="empty">Waiting for trusted local events…</p>'; }
  async function getJson(path) { const response=await fetch(path,{cache:"no-store",headers:{"Accept":"application/json"}}); if(!response.ok)throw new Error(`HTTP ${response.status}`); return response.json(); }
  async function refreshSnapshot() { try { await getJson(`${API}/health`); renderSnapshot(await getJson(`${API}/snapshot`)); } catch { markDisconnected(); } }
  async function refreshEvents() { try { (await getJson(`${API}/events`)).forEach(addEvent); renderEvents(); } catch { markDisconnected(); } }
  function markDisconnected() { connection("disconnected","DISCONNECTED"); if(state.snapshot){const age=Math.max(0,Math.floor((Date.now()-state.lastSuccess)/1000)); $("freshness").textContent=`STALE · ${age}s SINCE UPDATE`;} }
  function connectEvents() { if(state.eventSource)state.eventSource.close(); const source=new EventSource(`${API}/events/stream`); state.eventSource=source; source.onopen=()=>{connection("live","LIVE"); refreshSnapshot();}; source.onerror=()=>markDisconnected(); ALL_STATES.forEach(()=>{}); source.onmessage=consume; ["system_ready","system_idle","voice_listening","voice_speaking","task_started","task_completed","task_failed","latest_turn_updated","route_selected","route_fallback","node_ineligible","mo2_running","endpoint_unhealthy","qwen_started","qwen_completed","glm_started","glm_completed","memory_requested","memory_selected","no_applicable_memory","memory_conflict","memory_unavailable","tool_started","tool_completed","tool_failed","tests_started","tests_passed","tests_failed","review_started","review_completed","adjudication_completed"].forEach(type=>source.addEventListener(type,consume)); }
  function consume(message) { try { const event=JSON.parse(message.data); addEvent(event); renderEvents(); if(["system_ready","system_idle","voice_listening","voice_speaking","task_started","task_completed","task_failed","latest_turn_updated","mo2_running","tests_passed","tests_failed","review_completed","adjudication_completed"].includes(event.event_type))refreshSnapshot(); } catch { /* malformed observer data is ignored */ } }
  function tick() { $("clock").textContent=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}); if(document.body.dataset.connection==="disconnected"&&state.lastSuccess)markDisconnected(); }
  const ptt={phase:"idle",source:null,token:null,stream:null,context:null,processor:null,chunks:[],sampleRate:0,spaceHeld:false,spaceGeneration:null,intent:false,chunkTimer:null,chunkBusy:false,generation:0};
  function pttAllowed(){const systemState=document.body.dataset.systemState;const atSafeRest=["idle","completed","failed"].includes(systemState);return (ptt.phase==="idle"&&atSafeRest)||(ptt.phase==="submitting"&&systemState==="speaking");}
  function updatePTTAvailability(){const button=$("ptt-button");const allowed=pttAllowed()||ptt.phase==="capturing"||ptt.phase==="starting";button.disabled=!allowed;button.setAttribute("aria-disabled",String(!allowed));}
  function pttMessage(label,detail){$("ptt-status").textContent=label;$("ptt-detail").textContent=detail;}
  function editableTarget(target){if(!(target instanceof Element))return false;if(document.designMode==="on")return true;return Boolean(target.closest("input,textarea,select,[contenteditable]:not([contenteditable='false']),[role='textbox'],[role='searchbox'],[role='combobox']"));}
  function stopMedia(){if(ptt.processor){ptt.processor.disconnect();ptt.processor.onaudioprocess=null;}if(ptt.stream)ptt.stream.getTracks().forEach(track=>track.stop());if(ptt.context)ptt.context.close().catch(()=>{});ptt.processor=ptt.stream=ptt.context=null;}
  function resetPTT(){stopMedia();if(ptt.chunkTimer)clearInterval(ptt.chunkTimer);ptt.chunkTimer=null;ptt.chunkBusy=false;ptt.phase="idle";ptt.source=ptt.token=null;ptt.chunks=[];ptt.intent=false;const button=$("ptt-button");button.dataset.active="false";button.setAttribute("aria-pressed","false");updatePTTAvailability();}
  async function postJson(path,value){const response=await fetch(`${API}${path}`,{method:"POST",cache:"no-store",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify(value)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error?.message||`HTTP ${response.status}`);return data;}
  async function beginPTT(source){if(!pttAllowed())return;const generation=++ptt.generation;ptt.phase="starting";ptt.source=source;ptt.intent=true;updatePTTAvailability();pttMessage("REQUESTING MICROPHONE","Allow microphone access to begin this explicit hold.");try{const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(generation!==ptt.generation||!ptt.intent){stream.getTracks().forEach(track=>track.stop());return;}const AudioContext=window.AudioContext||window.webkitAudioContext;const context=new AudioContext();await context.resume();const sourceNode=context.createMediaStreamSource(stream);const processor=context.createScriptProcessor(4096,1,1);ptt.stream=stream;ptt.context=context;ptt.processor=processor;ptt.sampleRate=context.sampleRate;ptt.chunks=[];processor.onaudioprocess=event=>{if(ptt.phase==="capturing")ptt.chunks.push(new Float32Array(event.inputBuffer.getChannelData(0)));};sourceNode.connect(processor);processor.connect(context.destination);const begun=await postJson("/ptt/begin",{});if(generation!==ptt.generation||!ptt.intent){await postJson("/ptt/cancel",{turn_token:begun.turn_token}).catch(()=>{});return;}ptt.token=begun.turn_token;ptt.phase="capturing";ptt.chunkTimer=setInterval(offerPTTChunk,1000);$("ptt-button").dataset.active="true";$("ptt-button").setAttribute("aria-pressed","true");updatePTTAvailability();pttMessage("MICROPHONE ACTIVE","Release to stop capture and finalize locally.");}catch(error){if(generation===ptt.generation){resetPTT();pttMessage("MICROPHONE UNAVAILABLE",error?.message||"Permission denied or no microphone is available.");}}}
  function encodeWav(chunks,sampleRate){const length=chunks.reduce((sum,item)=>sum+item.length,0);const buffer=new ArrayBuffer(44+length*2);const view=new DataView(buffer);const ascii=(offset,value)=>{for(let i=0;i<value.length;i++)view.setUint8(offset+i,value.charCodeAt(i));};ascii(0,"RIFF");view.setUint32(4,36+length*2,true);ascii(8,"WAVE");ascii(12,"fmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);ascii(36,"data");view.setUint32(40,length*2,true);let offset=44;chunks.forEach(chunk=>chunk.forEach(sample=>{const bounded=Math.max(-1,Math.min(1,sample));view.setInt16(offset,bounded<0?bounded*32768:bounded*32767,true);offset+=2;}));return buffer;}
  async function offerPTTChunk(){if(ptt.phase!=="capturing"||ptt.chunkBusy||!ptt.token||!ptt.chunks.length)return;ptt.chunkBusy=true;const wav=encodeWav(ptt.chunks,ptt.sampleRate);try{await fetch(`${API}/ptt/chunk`,{method:"POST",cache:"no-store",headers:{"Accept":"application/json","Content-Type":"audio/wav","X-GRACI-PTT-Token":ptt.token},body:wav});}catch(_error){}finally{ptt.chunkBusy=false;}}
  async function finishPTT(expectedGeneration=ptt.generation){if(expectedGeneration!==ptt.generation)return;ptt.intent=false;if(ptt.phase==="starting"){++ptt.generation;resetPTT();return;}if(ptt.phase!=="capturing")return;const generation=ptt.generation;ptt.phase="submitting";const token=ptt.token;const wav=encodeWav(ptt.chunks,ptt.sampleRate);stopMedia();$("ptt-button").dataset.active="false";$("ptt-button").setAttribute("aria-pressed","false");updatePTTAvailability();pttMessage("TRANSCRIBING","Microphone off. Local transcription and governed processing in progress.");ptt.token=null;ptt.chunks=[];try{const response=await fetch(`${API}/ptt/finish`,{method:"POST",cache:"no-store",headers:{"Accept":"application/json","Content-Type":"audio/wav","X-GRACI-PTT-Token":token},body:wav});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error?.message||`HTTP ${response.status}`);await refreshSnapshot();if(generation===ptt.generation)pttMessage("TURN COMPLETE","Validated resident result shown.");}catch(error){if(generation===ptt.generation)pttMessage("TURN FAILED",error?.message||"The local GRACI backend is unavailable.");}finally{if(generation===ptt.generation)resetPTT();}}
  async function cancelPTT(reason){ptt.intent=false;if(ptt.phase==="idle"||ptt.phase==="submitting")return;const token=ptt.token;resetPTT();pttMessage("MICROPHONE OFF",reason);if(token)await postJson("/ptt/cancel",{turn_token:token}).catch(()=>{});}
  async function restartRuntime(){const button=$("restart-button");button.disabled=true;pttMessage("RESTARTING GRACI","Clearing transient local runtime state.");try{await postJson("/restart",{});resetPTT();await refreshSnapshot();pttMessage("GRACI READY","Runtime recovered; the latest completed result was retained.");}catch(error){pttMessage("RESTART FAILED",error?.message||"Local runtime recovery failed.");}finally{button.disabled=false;}}
  function installPTT(){const button=$("ptt-button");updatePTTAvailability();$("restart-button").addEventListener("click",restartRuntime);button.addEventListener("pointerdown",event=>{if(event.button!==0||!pttAllowed())return;event.preventDefault();button.setPointerCapture(event.pointerId);beginPTT("pointer");});button.addEventListener("pointerup",event=>{if(ptt.source!=="pointer")return;event.preventDefault();finishPTT();});["pointercancel","lostpointercapture"].forEach(type=>button.addEventListener(type,()=>{if(ptt.source==="pointer")cancelPTT("Capture interrupted safely.");}));window.addEventListener("keydown",event=>{if(event.code!=="Space"||event.repeat||ptt.spaceHeld||editableTarget(event.target)||!pttAllowed())return;event.preventDefault();ptt.spaceHeld=true;beginPTT("space");ptt.spaceGeneration=ptt.generation;});window.addEventListener("keyup",event=>{if(event.code!=="Space"||!ptt.spaceHeld)return;event.preventDefault();const generation=ptt.spaceGeneration;ptt.spaceHeld=false;ptt.spaceGeneration=null;if(ptt.source==="space"&&generation!==null)finishPTT(generation);});window.addEventListener("blur",()=>{ptt.spaceHeld=false;ptt.spaceGeneration=null;cancelPTT("Window focus changed; capture cancelled.");});document.addEventListener("visibilitychange",()=>{if(document.hidden){ptt.spaceHeld=false;ptt.spaceGeneration=null;cancelPTT("Page hidden; capture cancelled.");}});window.addEventListener("pagehide",()=>{ptt.spaceHeld=false;ptt.spaceGeneration=null;cancelPTT("Page closed; capture cancelled.");});}
  async function start() { installPTT(); tick(); setInterval(tick,1000); await Promise.allSettled([refreshSnapshot(),refreshEvents()]); connectEvents(); setInterval(refreshSnapshot,SNAPSHOT_INTERVAL_MS); }
  start();
})();
